$terminal = foot

monitor=Virtual-1,3440x1440@60,auto,1

workspace = 1, layout:scrolling

input {
	kb_layout = de
}
bind = SUPER, Return, 	exec, $terminal
bind = SUPER, Q,	killactive
bind = SUPER, M, 	exit
bind = SUPER, SPACE, 	exec, fuzzel

bind = SUPER, LEFT, 	movefocus, l
bind = SUPER, RIGHT, 	movefocus, r
bind = SUPER, UP, 	movefocus, u
bind = SUPER, DOWN, 	movefocus, d
